jemmia-diamond/fn

- src/services/erp/crm/lead/lead.js
Enhancement
___
- Add diamond note field to lead data processing
___
```mermaid
flowchart LR
A["Lead Data"] --> B["Process Raw Data"]
B --> C["Extract Diamond Note"]
C --> D["Add to Notes Array"]
D --> E["Updated Lead Data"]
```
<tr>
<td>
<details>
<summary><strong>lead.js</strong><dd><code>Add diamond note processing to lead service</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/services/erp/crm/lead/lead.js
<ul><li>Add conditional check for <code>diamond_note</code> field in raw data<br> <li> Push diamond note to …
> feat: add more note for lead

- src/services/ecommerce/product/utils/jewelry.js
Enhancement
___
- Modified jewelry query to include men's wedding rings
- Updated product filtering logic for wedding ring categories
___
```mermaid
flowchart LR
A["Product Query"] --> B["Filter Logic"]
B --> C["Exclude Wedding Rings"]
B --> D["Include Men's Wedding Rings"]
C --> E["Other Products"]
D --> F["Men's Wedding Rings Only"]
```
<tr>
<td>
<details>
<summary><strong>jewelry.js</strong><dd><code>Update wedding ring filter for men's products</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
> Feature: return more men wedding rings for ecom

- wrangler.jsonc
Enhancement
___
- Add Cloudflare KV namespace configuration
- Configure `FN_KV` binding for key-value storage
___
```mermaid
flowchart LR
A["wrangler.jsonc"] --> B["KV Namespace"]
B --> C["FN_KV Binding"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>wrangler.jsonc</strong><dd><code>Add KV namespace configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
wrangler.jsonc
<ul><li>Add <code>kv_namespaces</code> configuration …
> Feature/ Add KV Cloudflare

- src/controllers/erp/order-controller.js
- src/services/erp/selling/index.js
- src/services/erp/selling/sales-order/sales-order.js
- src/services/queue-handler.js
Enhancement
___
- Rename `OrderService` to `SalesOrderService` for clarity
- Update import paths to use `src/` prefix consistently
- Refactor variable names to match service rename
- Maintain consistent naming throughout codebase
___
```mermaid
flowchart LR
A["OrderService"] --> B["SalesOrderService"]
C["Relative imports"] --> D["src/ prefixed imports"]
E["orderData variables"] --> F["salesOrderData variables"]
```
<tr>
<td>
<details>
<summary><strong>order-controller.js</strong><dd><code>Update controller to use renamed service</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> Fix: Rename order service

- src/index.js
Enhancement
___
- Add CORS middleware to ecommerce API routes
- Support wildcard domain patterns for origin validation
- Configure allowed headers and HTTP methods
___
```mermaid
flowchart LR
A["Environment CORS_ORIGINS"] --> B["CORS Middleware"]
B --> C["Origin Validation"]
C --> D["Wildcard Pattern Matching"]
D --> E["Ecommerce Routes"]
```
<tr>
<td>
<details>
<summary><strong>index.js</strong><dd><code>Add CORS middleware for ecommerce API</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> Feature: CORS for Ecommerce API

- src/index.js
> Revert "Feature: CORS for Ecommerce API"

- src/controllers/ecommerce/product-controller.js
Enhancement
___
- Add `pages` parameter to product query filtering
- Support comma-separated page values in API requests
___
```mermaid
flowchart LR
A["Query Parameters"] --> B["Parse pages param"]
B --> C["Split comma-separated values"]
C --> D["Product Service"]
```
<tr>
<td>
<details>
<summary><strong>product-controller.js</strong><dd><code>Add pages parameter support</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary> …
> enhance: add pages to query params

- src/controllers/ecommerce/product-controller.js
- src/index.js
- src/services/ecommerce/product/product.js
- src/services/ecommerce/product/utils/jewelry.js
Bug fix
___
- Fix duplicate variants in jewelry search query
- Optimize image aggregation with subquery approach
- Minor formatting improvements in SQL queries
___
```mermaid
flowchart LR
A["Original Query"] --> B["Duplicate Variants Issue"]
B --> C["Image Subquery Solution"]
C --> D["Fixed Query Results"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Formatting</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>product.js</strong><dd><code>SQL formatting cleanup</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> Enhance: handle duplicate variants and filters on fineness and price

- src/controllers/redirect-controller.js
- src/index.js
- src/routes/app.js
- src/routes/index.js
Enhancement
___
- Add URL redirect functionality with predefined mappings
- Create new redirect controller for handling redirects
- Register app routes for redirect endpoints
- Integrate redirect routes into main application
___
```mermaid
flowchart LR
A["Client Request"] --> B["/redirects/:name endpoint"]
B --> C["RedirectController.show()"]
C --> D["Check MAPPINGS"]
D --> E["Return 404"] 
D --> F["Redirect to URL"]
```
<tr>
<td>
<details>
<summary><strong>redirect-controller.js</strong><dd><code>Create redirect controller with URL mappings</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> feat: add redirects feature

- prisma/schema/larksuite.prisma
- prisma/schema/migrations/20250808062818_00002/migration.sql
- prisma/schema/schema.prisma
- src/services/larksuite/docs/base/index.js
- src/services/larksuite/docs/base/record/record.js
- src/services/larksuite/docs/constant.js
- src/services/larksuite/docs/index.js
- src/services/larksuite/index.js
- src/services/larksuite/lark.js
- src/services/schedule-handler.js
Enhancement
___
- Add Lark Base table record synchronization service
- Create database schema for storing Larksuite records
- Implement pagination utility for API requests
- Schedule daily sync of debt tracking records
___
```mermaid
flowchart LR
A["Lark Base API"] --> B["RecordService"]
B --> C["Database Storage"]
D["Schedule Handler"] --> B
E["Pagination Utility"] --> A
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>8 files</summary><table>
<tr>
<td><strong>record.js</strong><dd><code>Core record synchronization service implementation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
<td><a …
> feature: sync lark base table record

- .husky/pre-commit
- README.md
- eslint.config.mjs
- package.json
- pnpm-lock.yaml
Other
___
- Setup Husky pre-commit hook for linting
- Add GitHub pull request template
- Configure npm scripts for formatting
___
```mermaid
flowchart LR
A["Developer commits"] --> B["Husky pre-commit hook"]
B --> C["pnpm lint execution"]
C --> D["Code quality check"]
E["PR creation"] --> F["Template guides"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>pull_request_template.md</strong><dd><code>Add GitHub pull request template</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> Setup husky pre-commit lint hook

- src/controllers/ecommerce/index.js
- src/controllers/ecommerce/product-controller.js
- src/index.js
- src/routes/index.js
- src/routes/public-api.js
- src/services/ecommerce/product/product.js
Enhancement
___
- Add public API endpoint for product retrieval
- Implement ProductController with error handling
- Integrate Haravan API for product data
- Create public router without authentication
___
```mermaid
flowchart LR
A["Public API Request"] --> B["ProductController.show"]
B --> C["ProductService.getProductById"]
C --> D["Haravan API"]
D --> E["Product Data Response"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>index.js</strong><dd><code>Add ProductController to exports</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> feat: add public router and public API to get product by ID

- src/services/erp/selling/sales-order/sales-order.js
Enhancement
___
- Add exception handling to `dequeueOrderQueue` method
- Wrap `processHaravanOrder` call in try-catch block
- Log errors to console for debugging
___
```mermaid
flowchart LR
A["dequeueOrderQueue method"] --> B["processHaravanOrder call"]
B --> C["try-catch wrapper"]
C --> D["error logging"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Error handling</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>sales-order.js</strong><dd><code>Add exception handling to order processing</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
> enhance: handle exception when dequeue order events

- src/services/ecommerce/order/ind-day-stat.js
Bug fix, Enhancement
___
- Fix Cloudflare dequeue issues with order processing
- Update Independent Day statistics configuration
- Change product ID and budget values
- Fix line items processing and cancellation logic
___
```mermaid
flowchart LR
A["Order Message"] --> B["IndDayStatService"]
B --> C["Process Line Items"]
C --> D["Update Budget Counters"]
D --> E["Handle Cancellation Status"]
```
<tr>
<td>
<details>
<summary><strong>ind-day-stat.js</strong><dd><code>Fix dequeue issues and update config</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> fix: fix cloudflare dequeue issues and update ind stats config

- src/services/ecommerce/order/ind-day-stat.js
Bug fix, Enhancement
___
- Remove order counting functionality and focus on product quantity tracking
- Fix Cloudflare dequeue issues with improved order status filtering
- Add timestamp validation for cancelled order processing
- Simplify KV storage operations by removing redundant keys
___
```mermaid
flowchart LR
A["Order Event"] --> B["Check partially_paid status"]
B --> C["Calculate Product Quantity"]
C --> D["Update KV Storage"]
D --> E["Validate Budget Limits"]
F["Cancelled Orders"] --> G["Timestamp Validation"]
G --> H["Subtract Quantity if Recent"]
```
<tr>
<td>
<details> …
> fix: remove the count_order key and fix the cloudflare dequeue issues

- src/services/ecommerce/order-tracking/order-tracking.js
Enhancement
___
- Replace hardcoded Haravan API key with secret store
- Move HaravanClient instantiation to method level
- Improve security by using environment secret management
___
```mermaid
flowchart LR
A["Constructor"] --> B["Remove HaravanClient instance"]
C["getOrder method"] --> D["Fetch API key from secret store"]
D --> E["Create HaravanClient instance"]
E --> F["Make API request"]
```
<tr>
<td>
<details>
<summary><strong>order-tracking.js</strong><dd><code>Replace hardcoded API key with secret store</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> Fix: use haravan token secret key

- src/controllers/webhook/haravan/erp/order.js
- src/services/ecommerce/enum.js
- src/services/ecommerce/zalo-message/enums/zalo-template.enum.js
- src/services/ecommerce/zalo-message/utils/format-template-zalo.js
- src/services/ecommerce/zalo-message/zalo-message.js
- src/services/queue-handler.js
Enhancement
___
- Route paid orders to Zalo message queue
- Update Zalo template configuration and data formatting
- Add order status enum and enhanced template data
- Rename queue handler method for clarity
___
```mermaid
flowchart LR
A["Haravan Webhook"] --> B["Order Controller"]
B --> C{Order Status}
C -->|Paid| D["Zalo Message Queue"]
C -->|Other| E["Order Queue"]
D --> F["Zalo Message Service"]
F --> G["Enhanced Template"]
```
<tr>
<td>
<details>
<summary><strong>order.js</strong><dd><code>Add paid order routing to Zalo queue</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> fix the zalo send

- src/services/larksuite/docs/base/record/record.js
- src/services/product_quote/order/order.js
Bug fix
___
- Fix 403 permission error in Lark record operations
- Change user ID type from "user_id" to "open_id"
- Refactor method signatures to use object parameters
- Update method calls to match new parameter structure
___
```mermaid
flowchart LR
A["RecordService methods"] -- "change user_id_type" --> B["open_id instead of user_id"]
A -- "refactor parameters" --> C["object destructuring"]
D["ProductQuoteOrderService"] -- "update method calls" --> A
```
<tr>
<td>
<details>
<summary><strong>record.js</strong><dd><code>Refactor record methods with open_id user type</code>&nbsp; &nbsp; &nbsp; &nbsp; …
> try fixing 403 error updating records on lark (production only)

- src/services/larksuite/contact/user/user.js
Enhancement
___
- Implement pagination for Larksuite user requests
- Replace Promise.all with sequential processing for departments
- Remove deprecated `findUsersByDepartment` method
- Use centralized `requestWithPagination` service method
___
```mermaid
flowchart LR
A["Department IDs"] --> B["Sequential Processing"]
B --> C["Paginated User Requests"]
C --> D["Flatten User Arrays"]
D --> E["Database Insert"]
```
<tr>
<td>
<details>
<summary><strong>user.js</strong><dd><code>Add pagination support for user synchronization</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> enhance: request Larksuite users with pagination

- src/services/ecommerce/order-tracking/order-tracking.js
- src/services/ecommerce/zalo-message/zalo-message.js
Bug fix
___
- Update database connection to use Neon provider
- Fix database initialization in order tracking service
- Fix database initialization in Zalo message service
___
```mermaid
flowchart LR
A["Database.instance(env)"] -- "changed to" --> B["Database.instance(env, 'neon')"]
B --> C["Order Tracking Service"]
B --> D["Zalo Message Service"]
```
<tr>
<td>
<details>
<summary><strong>order-tracking.js</strong><dd><code>Add Neon provider to database initialization</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
> fix(tracking): fix temp change prisma to neon

- prisma/schema/erpnext.prisma
- prisma/schema/migrations/20250905042621_add_promotion_purpose_category_tables/migration.sql
- src/services/erp/selling/index.js
- src/services/erp/selling/product-category/product-category.js
- src/services/erp/selling/promotion/promotion.js
- src/services/erp/selling/purchase_purpose/purchase_purpose.js
- src/services/schedule-handler.js
Enhancement
___
- Add three new ERPNext sync services for Promotion, Purchase Purpose, and Product Category tables
- Implement scheduled synchronization for new tables at 07:30 daily
- Create database models and migrations for the new tables
- Export new services through selling module index
___
```mermaid
flowchart LR
A["ERPNext API"] --> B["Sync Services"]
B --> C["Database Models"]
C --> D["Scheduled Jobs"]
B --> E["Service Exports"]
```
<tr>
<td>
<details>
<summary><strong>index.js</strong><dd><code>Export new sync services</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> feat(selling module): Sync Promotion, Purpose, Category tables from ERPNext

- src/services/erp/selling/sales-order/sales-order.js
- src/services/erp/selling/sales-order/utils/sales-order-notification.js
- src/services/haravan/products/product-variant/constant.js
- src/services/larksuite/group-chat/group-management/constant.js
Enhancement
___
- Enhanced sales order notification with customer data and validation
- Added new validation rules for policies and consultation date
- Improved message content with product categories and warranty policies
- Updated chat group routing for sales notifications
___
```mermaid
flowchart LR
A["Sales Order Data"] --> B["Customer Data Fetch"]
B --> C["Enhanced Validation"]
C --> D["Compose Rich Notification"]
D --> E["Send to Sales Chat Group"]
```
<tr>
<td>
<details>
<summary><strong>sales-order.js</strong><dd><code>Add customer data integration and routing update</code>&nbsp; &nbsp; …
> feat(sales-order-notification): more message content and validation

- src/services/erp/crm/lead/lead.js
Bug fix
___
- Enhanced error logging in lead service update method
___
<tr>
<td>
<details>
<summary><strong>lead.js</strong><dd><code>Enhanced error logging output</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/services/erp/crm/lead/lead.js
- Added error object to console.warn statement for better debugging
</details>
</td>
<td><a href="https://github.com/jemmia-diamond/fn/pull/191/files#diff-78a676ea3f303d19fbb2fac3eb05a628a42d …
> chore(erp): fix log

- src/services/ecommerce/product/utils/jewelry.js
Enhancement
___
- Migrate from regular tables to materialized views
- Simplify has_360 field logic using precomputed values
- Update table references and column mappings
- Remove redundant JOIN and CASE statement
___
```mermaid
flowchart LR
A["ecom.products"] --> B["ecom.materialized_products"]
C["ecom.variants"] --> D["ecom.materialized_variants"]
E["Complex CASE logic"] --> F["Precomputed has_360 field"]
G["workplace.ecom_360 JOIN"] --> H["Removed JOIN"]
```
<tr>
<td>
<details>
<summary><strong>jewelry.js</strong><dd><code>Migrate to materialized views and simplify queries</code>&nbsp; &nbsp; …
> refactor(jewelry-api): migrate to material view

- src/services/erp/crm/lead/lead.js
Bug fix
___
- Fixed SQL syntax error in lead query
- Corrected missing closing quote in WHERE clause
- Moved semicolon to proper position
___
```mermaid
flowchart LR
A["SQL Query"] -- "fix syntax" --> B["Corrected Query"]
B --> C["Proper WHERE clause"]
B --> D["Semicolon placement"]
```
<tr>
<td>
<details>
<summary><strong>lead.js</strong><dd><code>SQL syntax error correction</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary> …
> fix(erp-lead-api): fix sql syntax

- src/services/db-operations/index.js
- src/services/db-operations/materialized-view/materialized-view.js
- src/services/schedule-handler.js
Enhancement
___
- Add MaterializedViewService for database view refresh operations
- Integrate scheduled refresh for reporting and CRM views
- Configure 20-minute refresh cycle for reporting views
- Configure 30-minute refresh cycle for CRM dashboard views
___
```mermaid
flowchart LR
A["MaterializedViewService"] --> B["20min Refresh"]
A --> C["30min Refresh"]
B --> D["Reporting Views"]
C --> E["CRM Dashboard Views"]
F["Schedule Handler"] --> A
```
<tr>
<td>
<details>
<summary><strong>index.js</strong><dd><code>Add database operations module exports</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> Feat(database): Add function to refresh materialized view

- src/services/erp/selling/sales-order/sales-order.js
- src/services/erp/selling/sales-order/utils/sales-order-notification.js
Enhancement
___
- Enhanced sales order notification with customer journey and primary sales person
- Added validation for customer journey and primary sales person fields
- Improved message formatting with bold headers
- Reorganized notification content structure
___
```mermaid
flowchart LR
A["Sales Order Data"] --> B["Fetch Primary Sales Person"]
B --> C["Compose Enhanced Notification"]
C --> D["Validate Required Fields"]
D --> E["Send Lark Message"]
```
<tr>
<td>
<details>
<summary><strong>sales-order.js</strong><dd><code>Add primary sales person data fetching</code>&nbsp; &nbsp; &nbsp; &nbsp; …
> chore(sales-order-notification): more message content and validation

- src/services/ecommerce/product/product.js
- src/services/ecommerce/product/utils/wedding-ring.js
Enhancement
___
- Add `fineness` and `material_colors` metadata to wedding rings API
- Enhance count query to aggregate distinct metadata values
- Update response structure to include new metadata fields
___
```mermaid
flowchart LR
A["Wedding Rings Query"] --> B["Enhanced Count Query"]
B --> C["Aggregate Fineness"]
B --> D["Aggregate Material Colors"]
C --> E["API Response"]
D --> E
E --> F["Updated Metadata Structure"]
```
<tr>
<td>
<details>
<summary><strong>product.js</strong><dd><code>Enhanced wedding rings response with metadata</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> feat(wedding-rings-api): add fineness and material_colors metadata

- src/services/erp/crm/lead/lead.js
ignore update lead source and lead owner if updating
> fix(website-lead): ignore update lead source and lead owner if updating

- src/services/erp/selling/sales-order/utils/sales-order-notification.js
Other
___
- Replace empty lines with HTML break tags in notification template
- Improve formatting consistency across sales order notifications
___
```mermaid
flowchart LR
A["Empty lines"] -- "replaced with" --> B["HTML </br> tags"]
B --> C["Improved notification formatting"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Formatting</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>sales-order-notification.js</strong><dd><code>Replace empty lines with HTML breaks</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
> chore(notify-order): add break lines

- src/controllers/ecommerce/wedding-ring-controller.js
- src/services/ecommerce/product/utils/wedding-ring.js
[#253](https://github.com/jemmia-diamond/fn/issues/253)
Enhancement
___
- Add filter by band styles for wedding rings
- Parse ring_band_styles parameter from request
- Implement SQL filtering logic for band styles
- Support both formatted and plain band style values
___
```mermaid
flowchart LR
A["Request with ring_band_styles"] --> B["Parse band styles parameter"]
B --> C["Normalize styles to lowercase"]
C --> D["Build SQL filter conditions"]
D --> E["Filter wedding rings by band styles"]
```
<tr>
<td>
<details>
<summary><strong>wedding-ring-controller.js</strong><dd><code>Add band styles parameter …
> feat(website-combo): add filter by band styles for wedding rings

- src/services/erp/selling/sales-order/sales-order.js
- src/services/erp/selling/sales-order/utils/sales-order-notification.js
Other
___
- Update Lark client to use `createClientV2` method
- Change notification destination from SUPPORT_ERP_SALES to CUSTOMER_INFO
- Replace HTML break tags with newlines in notification content
___
```mermaid
flowchart LR
A["Sales Order Service"] --> B["Lark Client V2"]
A --> C["CUSTOMER_INFO Chat Group"]
D["HTML Break Tags"] --> E["Plain Newlines"]
```
<tr>
<td>
<details>
<summary><strong>sales-order.js</strong><dd><code>Update Lark client and notification group</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary> …
> chore(erp): move to correct group, fix break line

- src/services/erp/selling/sales-order/utils/sales-order-notification.js
- src/services/utils/string-helper.js
Bug fix
___
- Refactor message formatting for Lark notifications
- Replace string concatenation with proper template building
- Add specialized string squish function for Lark messages
- Fix newline handling and whitespace normalization
___
```mermaid
flowchart LR
A["stringSquish"] --> B["stringSquishLarkMessage"]
C["Template concatenation"] --> D["Structured content building"]
E["Newline handling"] --> F["Proper escape sequences"]
```
<tr>
<td>
<details>
<summary><strong>sales-order-notification.js</strong><dd><code>Refactor notification message composition for Lark</code>&nbsp; &nbsp; &nbsp; &nbsp; …
> fix(erp): format msg

- src/services/erp/selling/sales-order/utils/sales-order-notification.js
Bug fix
___
- Calculate remaining balance dynamically instead of using stored value
- Ensure balance accuracy by computing from grand total minus paid amount
___
```mermaid
flowchart LR
A["Sales Order Data"] --> B["Calculate Balance"]
B --> C["grand_total - paid_amount"]
C --> D["Display in Notification"]
```
<tr>
<td>
<details>
<summary><strong>sales-order-notification.js</strong><dd><code>Calculate balance dynamically in notification</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/services/erp/selling/sales-order/utils/sales-order-notifi …
> chore(erp): show balance by formula

- src/services/erp/selling/sales-order/utils/sales-order-notification.js
Bug fix
___
- Fix timezone conversion from UTC to ICT (Ho Chi Minh)
- Update date formatting to use Asia/Ho_Chi_Minh timezone
___
```mermaid
flowchart LR
UTC["UTC Time"] -- "convert to" --> ICT["ICT/Ho Chi Minh Time"]
ICT -- "format" --> Display["DD-MM-YYYY HH:mm:ss"]
```
<tr>
<td>
<details>
<summary><strong>sales-order-notification.js</strong><dd><code>Add timezone conversion to Ho Chi Minh time</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/services/erp/selling/sales-order/utils/sales-order-notification.js
<ul><li>Import …
> fix(erp): utc to ict date

- src/controllers/ecommerce/jewelry-controller.js
- src/services/ecommerce/product/utils/jewelry.js
Enhancement
___
- Add filter by linked collection functionality
- Extend jewelry query with collection joins
- Support multiple linked collections filtering
___
```mermaid
flowchart LR
A["Controller"] -- "parse linked_collections param" --> B["Product Service"]
B -- "build query with collection filter" --> C["Database Query"]
C -- "join haravan_collections table" --> D["Filtered Results"]
```
<tr>
<td>
<details>
<summary><strong>jewelry-controller.js</strong><dd><code>Add linked collections parameter parsing</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> feat(website): add filter by linked collection
